name: upload-to-s3

on:
  push:
    branches:
      - feat/gh-action-to-upload-to-s3

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.17.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          # TestNet S3 credentials are the same with Staging
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Prepare build folder
        run: node build.mjs

      - name: Upload to S3 bucket
        run: aws s3 sync ./build/ s3://asa-list --delete --acl=public-read

      - name: Remove build folder
        run: node cleanup.mjs
